server:
  port: 9059

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/ACLTest
    jdbc-url: jdbc:h2:tcp://localhost/~/ACLTest
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    #database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true